pipeline {
  agent any

  stages {
    stage('Build') {
      steps {
        script {
          docker.build('my-app') // Cambio en la carpeta de construcción
        }
      }
    }
    stage('Test') {
      steps {
        script {
          docker.image('my-app').inside {
            sh 'npm test'
          }
        }
      }
    }
    stage('Deploy') {
      steps {
        script {
          docker.image('my-app').run('-p 3000:3000')
        }
      }
    }
  }
}

